name: release

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: https://npm.pkg.github.com/ecotricity/
        scope: '@ecotricity'
    - run: npm ci
    - run: npm test